### ISSUE TITLE
Crash when starting up

### ISSUE THREAD

**Issue by thakyZ** [rumangerst/SilVerPLuM#1]
I am running on Windows 10. I changed one of my mod's files manually while the program was open and then restarted the program and it wouldn't open back up. I have attached a *.dmp file in the description
[SilVerPLuM.exe.16880.zip](https://github.com/rumangerst/SilVerPLuM/files/528307/SilVerPLuM.exe.16880.zip)

**Comment by rumangerst** [comment]
Can you send me the your whole profile that refuses to load?

**Comment by thakyZ** [comment]
Here you go:
[modded.zip](https://github.com/rumangerst/SilVerPLuM/files/529921/modded.zip)

**Comment by rumangerst** [comment]
Thank you for reporting. I think I fixed it (update is live now).

The problem was specific to the mod-manager (that does everything ID-based) and was caused by the sorting-function. std::sort sorts in-place and the calling method always uses a function in the mod-manager to get the priority from the settings. This function accesses the list that is currently being sorted, causing crazy behavior.
